spring: 
  application:
    name: sandpay-eurka-server
    
server: 
  port: 8061

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #false来表明自己是一个eureka server
    fetchRegistry: false #false来表明自己是一个eureka server
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

