spring: 
  application:
    name: sandpay-eurka-server
    
server: 
  port: 8061

spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: false #false来表明自己是一个eureka server
    fetchRegistry: false #false来表明自己是一个eureka server
    serviceUrl:
      defaultZone: http://peer1:8062/eureka/

