spring: 
  application:
    name: sandpay-eurka-server
    
server: 
  port: 8062

spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false #false来表明自己是一个eureka server
    fetchRegistry: false #false来表明自己是一个eureka server
    serviceUrl:
      defaultZone: http://peer1:8061/eureka/

